### ISSUE TITLE
frontend service container cann't connect with naming service

### ISSUE THREAD

**Issue by VincentLiu028** [Azure-Samples/service-fabric-containers#1]
After following step and run application in container mode, get below in frontend container log 
![image](https://user-images.githubusercontent.com/17308665/27077086-886627cc-5061-11e7-96f3-68fe4c93fe96.png)
I exec -it frontend container and run command to access naming service 
PowerShell -Command "(new-object net.webclient).DownloadString('http://172.30.48.1:19080/Services/Container.Application/BackEndService/$/ResolvePartition?api-version=1.0')"
Then get same error remote server not response 
![image](https://user-images.githubusercontent.com/17308665/27077171-c5975602-5061-11e7-91b9-b1a9ce20ae13.png)

**Comment by VincentLiu028** [comment]
It seems this problem only happens on local cluster. It doesn't repro with cluster on azure

**Comment by suhuruli** [comment]
Please update to the latest SDK and try. This was a networking issue with container to container communication on localhost.
