### ISSUE TITLE
Where is the docker-compose file?

### ISSUE THREAD

**Issue by haitaoxin** [Azure-Samples/service-fabric-containers#12]
Cannot deploy this sample app without that

**Comment by larryclaman** [comment]
same problem.  Linux/container-tutorial/readme.md references a docker-compose file, but I can't find one in the repo.

**Comment by suhuruli** [comment]
Hi, 

This has been resolved and should be reflected in the docs and Github repo soon. 

https://github.com/Azure-Samples/service-fabric-containers

The corresponding documentation

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-quickstart-containers-linux

Thanks,
Sudhanva
